
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Joti_One } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jotiOne = Joti_One({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={jotiOne.className}>
        <div style={{backgroundColor: 'rgba(224, 215, 223, 0.6)', overflowX: 'clip', position:'relative'}}>
          {children}
        </div>
      </body>
    </html>
  );
}
